# Generated by Django 5.2.5 on 2025-10-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('user', 'User'), ('dealer', 'Dealer'), ('vip', 'VIP'), ('partner', 'Partner')], default='user', help_text='User pricing level (hidden from users)', max_length=20),
        ),
    ]
