# Generated by Django 5.2.5 on 2025-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_customuser_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('user', 'User'), ('dealer', 'Dealer'), ('vip', 'VIP'), ('partner', 'Partner')], help_text='User level', max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for this level (e.g., 1.8 for 1.8x prices)', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Level Multiplier',
                'verbose_name_plural': 'User Level Multipliers',
                'ordering': ['level'],
            },
        ),
    ]
