# Generated by Django 5.2.5 on 2025-10-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_populate_user_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_level',
        ),
        migrations.DeleteModel(
            name='UserLevel',
        ),
    ]
