# Generated by Django 5.2.5 on 2025-10-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_remove_customuser_user_level_delete_userlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('USER', 'User'), ('DEALER', 'Dealer'), ('VIP', 'VIP'), ('PARTNER', 'Partner')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=1, default=1.8, help_text='Price multiplier for this level (e.g., 1.8 means prices are multiplied by 1.8)', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Level',
                'verbose_name_plural': 'User Levels',
                'ordering': ['multiplier'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.ForeignKey(blank=True, help_text="User's pricing level", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authorization.userlevel'),
        ),
    ]
