# Generated by Django 5.2.5 on 2025-10-16 16:42

from django.db import migrations
from decimal import Decimal


def populate_user_levels(apps, schema_editor):
    """Create default user levels with multipliers"""
    UserLevel = apps.get_model('authorization', 'UserLevel')
    
    levels = [
        {'name': 'USER', 'multiplier': Decimal('1.8')},
        {'name': 'DEALER', 'multiplier': Decimal('1.7')},
        {'name': 'VIP', 'multiplier': Decimal('1.6')},
        {'name': 'PARTNER', 'multiplier': Decimal('1.4')},
    ]
    
    for level_data in levels:
        UserLevel.objects.get_or_create(
            name=level_data['name'],
            defaults={'multiplier': level_data['multiplier'], 'is_active': True}
        )


def reverse_populate_user_levels(apps, schema_editor):
    """Remove all user levels"""
    UserLevel = apps.get_model('authorization', 'UserLevel')
    UserLevel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_userlevel_customuser_user_level'),
    ]

    operations = [
        migrations.RunPython(populate_user_levels, reverse_populate_user_levels),
    ]
