# Generated by Django 5.2.5 on 2025-09-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Display this brand on the homepage'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Display this product on the homepage'),
        ),
    ]
