# Generated by Django 5.2.5 on 2025-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_shipping_city_order_shipping_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Teluxe', max_length=100)),
                ('subtitle', models.CharField(default="Discover the finest luxury timepieces from the world's most prestigious brands", max_length=200)),
                ('background_image', models.ImageField(help_text='High-quality hero background image', upload_to='hero/')),
                ('button_text', models.CharField(default='Explore Collection', max_length=50)),
                ('button_url', models.CharField(default='/catalog/', help_text='URL the button should link to', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-created_at'],
            },
        ),
    ]
