# Generated by Django 5.2.5 on 2025-10-14 11:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shippingaddress_order_shipping_address_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gram', models.DecimalField(decimal_places=2, help_text='Price per gram in USD', max_digits=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=25.0, help_text='Markup percentage (default 25%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gold Price',
                'verbose_name_plural': 'Gold Prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=7000.0, help_text='Work price in USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this work price covers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Work Price',
                'verbose_name_plural': 'Work Prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_type',
            field=models.CharField(blank=True, choices=[('natural', 'Natural Diamond'), ('lab', 'Lab Diamond')], help_text='Type of diamonds used', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gold_weight_grams',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight of gold in grams', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='has_diamonds',
            field=models.BooleanField(default=False, help_text='Does this product include diamonds?'),
        ),
        migrations.CreateModel(
            name='DiamondPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_type', models.CharField(choices=[('natural', 'Natural Diamond'), ('lab', 'Lab Diamond')], max_length=20)),
                ('size_category', models.CharField(choices=[('under_5', 'Under 5 (2.22mm)'), ('5_to_7', '5 to 7 (3.57mm)'), ('8_to_12', '8 to 12 (1.85mm)'), ('13_to_17', '13 to 17 (0.16mm)')], max_length=20)),
                ('size_mm', models.DecimalField(decimal_places=2, help_text='Size in mm', max_digits=5)),
                ('quantity_for_price', models.IntegerField(help_text='Quantity for the given price')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the quantity in USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diamond Price',
                'verbose_name_plural': 'Diamond Prices',
                'ordering': ['diamond_type', 'size_category'],
                'unique_together': {('diamond_type', 'size_category')},
            },
        ),
        migrations.CreateModel(
            name='ProductDiamondOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_category', models.CharField(choices=[('under_5', 'Under 5 (2.22mm)'), ('5_to_7', '5 to 7 (3.57mm)'), ('8_to_12', '8 to 12 (1.85mm)'), ('13_to_17', '13 to 17 (0.16mm)')], max_length=20)),
                ('default_quantity', models.IntegerField(default=0, help_text='Default quantity for this size')),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum quantity allowed')),
                ('max_quantity', models.IntegerField(default=1000, help_text='Maximum quantity allowed')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diamond_options', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Diamond Option',
                'verbose_name_plural': 'Product Diamond Options',
                'ordering': ['size_category'],
                'unique_together': {('product', 'size_category')},
            },
        ),
    ]
