# Generated by Django 5.2.5 on 2025-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_goldprice_workprice_product_diamond_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='diamondprice',
            name='quantity_for_price',
        ),
        migrations.RemoveField(
            model_name='diamondprice',
            name='size_mm',
        ),
        migrations.AddField(
            model_name='diamondprice',
            name='carats_per_diamond',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Carat weight per diamond (e.g., 2.22)', max_digits=5),
        ),
        migrations.AddField(
            model_name='diamondprice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for this size category in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='diamondprice',
            name='size_category',
            field=models.CharField(choices=[('under_5', 'Under 5 (2.22 carats)'), ('5_to_7', '5 to 7 (3.57 carats)'), ('8_to_12', '8 to 12 (1.85 carats)'), ('13_to_17', '13 to 17 (0.16 carats)')], max_length=20),
        ),
    ]
