# Generated by Django 5.2.5 on 2025-10-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_diamondprice_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondprice',
            name='carats_per_diamond',
        ),
        migrations.RemoveField(
            model_name='diamondprice',
            name='total_price',
        ),
        migrations.AddField(
            model_name='diamondprice',
            name='carats_info',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Reference carat size (display only)', max_digits=5),
        ),
        migrations.AddField(
            model_name='diamondprice',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Price per unit - will be multiplied by user's quantity", max_digits=10),
        ),
        migrations.AlterField(
            model_name='diamondprice',
            name='size_category',
            field=models.CharField(choices=[('under_5', 'Under 5'), ('5_to_7', '5 to 7'), ('8_to_12', '8 to 12'), ('13_to_17', '13 to 17')], max_length=20),
        ),
    ]
