# Generated by Django 5.2.5 on 2025-10-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_diamondprice_carats_per_diamond_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_price_3b79b5_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost tracking only', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Not used. Price is calculated from gold weight.', max_digits=12, null=True),
        ),
    ]
