# Generated by Django 5.2.5 on 2025-10-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_stars',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
