# Generated by Django 5.2.5 on 2025-10-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_rating_stars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='country',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
    ]
