# Generated by Django 5.2.5 on 2025-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_brand_country_remove_brand_founded_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldprice',
            name='markup_percentage',
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Markup percentage (default 25%)', max_digits=5),
        ),
    ]
