# Generated by Django 5.2.5 on 2025-10-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_goldprice_markup_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondprice',
            name='carats_info',
        ),
        migrations.RemoveField(
            model_name='diamondprice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diamondprice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='diamondprice',
            name='updated_at',
        ),
    ]
