# Generated by Django 5.2.5 on 2025-10-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_diamondprice_carats_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workprice',
            name='is_active',
        ),
    ]
