# Generated by Django 5.2.5 on 2025-10-29 17:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_workprice_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diamond_type',
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_carats',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total carats of diamonds in this product', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_size',
            field=models.CharField(blank=True, choices=[('under_5', 'Under 5'), ('5_to_7', '5 to 7'), ('8_to_12', '8 to 12'), ('13_to_17', '13 to 17')], help_text='Size category of diamonds for this product', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
