# Generated by Django 5.2.7 on 2025-10-29 18:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_product_diamond_type_product_diamond_carats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text='Size label (e.g., 17mm, 19mm, 42mm, S, M, L, etc.)', max_length=50)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for this size (e.g., 1.0 = base price, 1.2 = 20% more)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default size?')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'ordering': ['product', 'sort_order'],
                'unique_together': {('product', 'size_label')},
            },
        ),
    ]
