# Generated by Django 5.2.7 on 2025-10-29 18:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diamond_carats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total carats of diamonds in this product', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
