# Generated by Django 5.2.5 on 2025-10-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_diamond_carats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
    ]
