# Generated by Django 5.2.5 on 2025-10-29 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='diamond_type',
            field=models.CharField(blank=True, choices=[('natural', 'Natural Diamond'), ('lab', 'Lab Diamond')], help_text='Type of diamond selected by user', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(blank=True, help_text='Selected size option', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productsize'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='customization_data',
            field=models.JSONField(blank=True, help_text='Store additional customization options', null=True),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='customization_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
